// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxljxtntxgyhkkmzxrcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bGp4dG50eGd5aGtrbXp4cmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTc4MDksImV4cCI6MjA1MDE5MzgwOX0.HaDXLGXJPAvPvpDz-Tx5VbLWWmauBgLXNHxAbPOOFnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);